patterns:
  - "R /data/"
  - "+ data/borgmatic/borg/config"
  - "+ data/overseerr/settings.json"
  - "+ data/sabnzbd/sabnzbd.ini"
  - "+ re:^data\/(lidarr|sonarr|radarr)\/config.xml"
  - "+ re:^data\/(plex|syncthing|wireguard|gitea|paperless|home-assistant)"
  - "- data/**"
repositories:
  - path: /storage/backup
    label: storage
  - path: ssh://${RSYNC_NET_USER}@${RSYNC_NET_HOST}/./homelab
    label: rsync_net
remote_path: borg12
sqlite_databases:
  - name: lidarr
    path: /data/lidarr/lidarr.db
  - name: radarr
    path: /data/radarr/radarr.db
  - name: sonarr
    path: /data/sonarr/sonarr.db
  - name: overseerr
    path: /data/overseerr/db/db.sqlite3
  - name: paperless
    path: /data/paperless/data/db.sqlite3
  - name: home-assistant
    path: /data/home-assistant/home-assistant_v2.db
postgresql_databases:
  - name: all
    hostname: immich-database
    username: ${IMMICH_DB_USER}
    password: ${IMMICH_DB_PASSWORD}
    options: --clean --if-exists
  - name: all
    hostname: gitea-db
    username: ${GITEA_DB_USER}
    password: ${GITEA_DB_PASSWORD}
    options: --clean --if-exists
store_config_files: true
keep_daily: 3
keep_weekly: 2
keep_monthly: 1
checks:
  - name: repository
  - name: archives
    frequency: 2 weeks
ssh_command: ssh -o StrictHostKeyChecking=no -i /run/secrets/rsync_net
archive_name_format: homelab-{now}
match_archives: sh:homelab-*
apprise:
  services:
    - url: ${PUSHOVER_URL}
      label: pushover
  send_logs: true
  logs_size_limit: 1024
  start:
    title: Borgmatic - homelab-data
    body: Started
  finish:
    title: Borgmatic - homelab-data
    body: Finished
  fail:
    title: Borgmatic - homelab-data
    body: Failed
  states:
    - start
    - finish
    - fail
