patterns:
  - "R /storage/"
  - "+ storage/photos"
  - "+ storage/media/music"
  - "- storage/**"
repositories:
  - path: ssh://${RSYNC_NET_USER}@${RSYNC_NET_HOST}/./storage
    label: rsync_net_storage
remote_path: borg12
store_config_files: true
keep_daily: 5
keep_weekly: 4
keep_monthly: 12
keep_yearly: 2
checks:
  - name: repository
  - name: archives
    frequency: 2 weeks
ssh_command: ssh -o StrictHostKeyChecking=no -i /run/secrets/rsync_net
archive_name_format: storage-{now}
match_archives: sh:storage-*
apprise:
  services:
    - url: ${PUSHOVER_URL}
      label: pushover
  send_logs: true
  logs_size_limit: 1024
  start:
    title: Borgmatic - storage
    body: Started
  finish:
    title: Borgmatic - storage
    body: Finished
  fail:
    title: Borgmatic - storage
    body: Failed
  states:
    - start
    - finish
    - fail
