- name: Create i915.conf
  ansible.builtin.copy:
    dest: /etc/modprobe.d/i915.conf
    content: |
      options i915 enable_guc=2
  notify:
    - Update initramfs
    - Reboot

- name: Flush handlers
  meta: flush_handlers
