- name: Ensure dependencies are installed.
  ansible.builtin.apt:
    name: nfs-common
    state: present

- name: Mount an NFS volume
  ansible.posix.mount:
    src: "{{ item.src }}"
    path: "{{ item.dest }}"
    opts: rw
    state: mounted
    fstype: nfs
    boot: true
  with_items: "{{ nfs_client_mounts }}"
