services:
  paperless-redis:
    image: docker.io/library/redis:7
    volumes:
      - paperless-redis:/data
    networks:
      homelab:
    restart: unless-stopped

  paperless:
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    environment:
      PAPERLESS_REDIS: redis://paperless-redis:6379
      PAPERLESS_URL: https://paperless.${HOMELAB_DOMAIN}
      PAPERLESS_TIME_ZONE: ${TZ}
      USERMAP_UID: ${PUID}
      USERMAP_GID: ${PGID}
    volumes:
      - /mnt/data/paperless:/usr/src/paperless/data
      - /mnt/storage/documents/paperless:/usr/src/paperless/media
      - paperless-consume:/usr/src/paperless/consume
    networks:
      homelab:
    labels:
      caddy: paperless.${HOMELAB_DOMAIN}
      caddy.import: common
      caddy.reverse_proxy: "{{upstreams 8000}}"
    depends_on:
      - paperless-redis
    restart: unless-stopped

  scan-hp:
    image: manuc66/node-hp-scan-to:master
    environment:
      - IP=10.0.1.208
      - LABEL=scan
      - PATTERN="scan"_dd.mm.yyyy_hh:MM:ss
      - PGID
      - PUID
      - TZ
    volumes:
      - paperless-consume:/scan
    restart: always

volumes:
  paperless-redis:
  paperless-consume:
